on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest', 'macos-14']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install -r ./PythonInterface/requirements.txt pyinstaller
      - name: Build with PyInstaller
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-pc-windows-msvc.exe
          elif [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-unknown-linux-gnu
          elif [[ ${{ matrix.os }} == "macos-latest" ]]; then
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-apple-darwin
          elif [[ ${{ matrix.os }} == "macos-14" ]]; then
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-aarch64-apple-darwin
          fi
