on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-12', 'flyci-macos-large-latest-m2', 'ubuntu-latest']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install -r ./PythonInterface/requirements.txt pyinstaller
      - name: Build with PyInstaller
        run: |
          $os = "${{ matrix.os }}"  # Set the operating system variable from matrix
          if ($os -eq "windows-latest") {
            New-Item -Path './PythonInterface/dist' -ItemType Directory
            cd ./PythonInterface/
            pyinstaller even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-pc-windows-msvc.exe
          } elseif ($os -eq "ubuntu-latest") {
            New-Item -Path './PythonInterface/dist' -ItemType Directory
            cd ./PythonInterface/
            pyinstaller even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-unknown-linux-gnu
          } elseif ($os -eq "macos-12") {
            New-Item -Path './PythonInterface/dist' -ItemType Directory
            cd ./PythonInterface/
            pyinstaller even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-apple-darwin
          } elseif ($os -eq "flyci-macos-large-latest-m2") {
            New-Item -Path './PythonInterface/dist' -ItemType Directory
            cd ./PythonInterface/
            pyinstaller even_photos_resolve.py --onefile --name even_photos_resolve-aarch64-apple-darwin
          }
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Executables
          path: ./PythonInterface/dist
          if-no-files-found: error

      - name: Install dependencies (ubuntu only)
        if: matrix.platform.os == 'ubuntu'
      # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './TauriApp/src-tauri -> target'

      # Setup Node.js for Tauri
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Tauri CLI
      - name: Install Tauri dependencies
        run: |
         cd TauriApp
         npm install

         - name: Build the app
         uses: tauri-apps/tauri-action@v0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
           releaseName: 'App v__VERSION__'
           releaseBody: 'See the assets to download this version and install.'
           releaseDraft: true
           prerelease: false
      # Upload Tauri Artifacts
      - name: Upload Tauri Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tauri Binaries
          path: ./TauriApp/src-tauri/target/release/bundle
          if-no-files-found: error