on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest', 'macos-14']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install -r ./PythonInterface/requirements.txt pyinstaller
      - name: Build with PyInstaller
        run: |
          if ($env:matrix_os -eq "windows-latest") {
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-pc-windows-msvc.exe
          } elseif ($env:matrix_os -eq "ubuntu-latest") {
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-unknown-linux-gnu
          } elseif ($env:matrix_os -eq "macos-latest") {
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-x86_64-apple-darwin
          } elseif ($env:matrix_os -eq "macos-14") {
            pyinstaller ./PythonInterface/even_photos_resolve.py --onefile --name even_photos_resolve-aarch64-apple-darwin
          }
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Executables
          path: dist/